### ISSUE TITLE
Patterns boolean algebra

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#106]
Brilliant idea by @vrom911 which I've implemented in #98, got me inspired. We could add the following constructors as well:

```haskell
PatternAnd Pattern Pattern
PatternNot Pattern
```

So we can define more flexible patterns. For example, functions `succ` and `pred` are partial for all types except `Integer`. `succ` is also not partial for `Natural`. So we could improve type patterns for them in the following way:

Current:

```haskell
succPat = (?)
predPat = (?)
```

After:

```haskell
succPat = PatternNot (integerNameMeta |-> (?)) &&& PatternNot (naturalNameMeta |-> (?))
predPat = PatternNot (integerNameMeta |-> (?))
```

**Comment by vrom911** [comment]
Wow, this is a neat idea! Such an elegant solution, I like it. Thanks, @chshersh :star_struck:

**Comment by chshersh** [comment]
It looks like we need this for both `Ast` and `Type`, so we can introduce a type like:

```haskell
data BoolExp  -- TODO: better name
    = Is a
    | Not (BoolExp a)
    | Or (BoolExp a) (BoolExp a)
    | And (BoolExp a) (BoolExp a)
```

**Comment by chshersh** [comment]
As we probably need the same construction in the `PatternAst` type, We can introduce the following data type:

```haskell
data BoolExp a  -- TODO: better name required
    = Is a  -- a; TODO: other names than 'Is'?
    | Not a  -- not a
    | And (BoolExp a) (BoolExp a)  -- a && b
    | Or (BoolExp a) (BoolExp a)  -- a || b
```

And a function like this:

```haskell
evalBoolExp :: (a -> Bool) -> BoolExp a -> Bool
```

And all matching functions will work with `BoolExp smth` instead of having `smth` with `PatternOr` constructors inside. What do you think?

**Comment by chshersh** [comment]
On the other hand, we might want to just duplicate the constructors and implement the true _Final Taggless_ with typeclasses for our eDSL (as proposed by @vrom911).

I realized that a separate `BoolExp` type might not be convenient if I want to use `PatternOr` only for a sub-part of a pattern. Let's say, I want to capture the following two syntax trees with a single pattern:

```haskell
for_ [1 .. 1000]
for_ [1 .. n]
```

I **can't** do that is `BoolExp` is a separate type. Supporting a separate type will require to have mutually-recursive data types, and this is a nightmare. But with `PatternOn` inside `PatternAst` (and `PatternType`) I can do something like this (in a pseudo-eDSL):

```haskell
app forName $ range anyConstant (anyConstant ||| anyVariable)
```

With a separate `BoolExp`:

```haskell
app forName (range anyConstant anyConstant)
    |||
app forName (range anyConstant anyVariable)
```

Not so convenient :unamused:
