### ISSUE TITLE
CLI for specifying checks

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#123]
Since we have them in config, it could be a good idea to specify them in the CLI as well. The only problem: how to specify them in CLI?

I see two possible options, but I'm not sure, whether `optparse-applicative` supports them, or how to implement them.

1. **Repeat the `check` command multiple times.** The CLI will look like this:
    ```shell
    $ stan \
        check --type=Include --inspectionId=STAN-0000 \
        check --type=Ignore --observationId=bla-bla
    ```
2. **Specify arguments as a substring for the `check` option.** The CLI will look like this:
    ```shell
    $ stan \
        --check="--type=Include --inspectionId=STAN-0000" \
        --check="--type=Ignore --observationId=bla-bla"
    ```
    `optparse-applicative` has the [execParserPure](https://hackage.haskell.org/package/optparse-applicative-0.15.1.0/docs/Options-Applicative.html#v:execParserPure) function, so maybe it can be reused.

**Comment by vrom911** [comment]
Yes, thanks for the summary, @chshersh !
If the first case is a valid one in CLI I would like to have it. It seems more natural to me :slightly_smiling_face:

**Comment by chshersh** [comment]
@vrom911 I agree. If it's possible to implement the first option, then let's go for it. It also looks much cleaner to me :slightly_smiling_face:
