### ISSUE TITLE
Should we support 'version' in config?

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#126]
I imagine, that the TOML schema in `stan` can evolve in some ways. So maybe it's worth it to introduce an enum like `ConfigVersion` and use codec depending on that version?

**Open question:** What to do when the version is not specified?
    1. Use the latest
    2. Use first
    3. Fail with error

**Comment by vrom911** [comment]
What the version should affect? The list of inspections? Or something else? Should the report also be versioned?

**Comment by chshersh** [comment]
@vrom911 The version would affect, how `stan` will parse the config. For example, if we decide to change TOML schema (rename fields, change types of some fields, etc.), different versions of `stan` will behave differently on the same config, but if we support versions, we can change the schema and users can upgrade to newer versions of `stan` without changing their TOML config.

Thinking about this more, I now see that supporting versions will bring more headache to the project rather than benefits. For now, I don't see how the schema can change drastically very soon. So I'll close the issue for now, but we can return to it back in the future if we decide to support versioning.
