### ISSUE TITLE
Command to turn TOML config into CLI line to use

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#134]
It could be useful for reproducibility

**Comment by vrom911** [comment]
I think it shoudl be another command. Something like:

```shell
stan config-to-command
```

This should find the default (if present) and return the command that the user can just copy-paste into the terminal.

Also, it should have an optional field with the path to a config file.

What do you think @chshersh ?
Another option could be to make the path option mandatory.

**Comment by chshersh** [comment]
@vrom911 I agree that this should be a separate command. And I think it's okay if it will find the default config :+1:
