### ISSUE TITLE
Remove 'CheckObservation' filter and create a separate field in Config for ignoring observations

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#143]

**Comment by chshersh** [comment]
@vrom911 Do you think it's a good idea to have a top-level array of strings to ignore observations? In TOML it will look like this:

```toml
ignoreObservations =
    [ "OBS-STAN-0103-YrzpQi-27:34"
    , "OBS-STAN-0106-cpLcRq-24:15"
    , "..."
    ]
```

**Comment by vrom911** [comment]
Yes, that looks legit :ok_hand:

**Comment by chshersh** [comment]
@vrom911 another question: since we moving `Observation`s out of `[[check]]`, would it be a good idea to rename `inspectionId` to simply `id`? Or it's better to still be more explicit? I was just thinking about possible ways to simplify config... :thinking:

**Comment by vrom911** [comment]
Yes, good catch, `id` would be better in here afterwards :100:
