### ISSUE TITLE
Property test on double applyChecks

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#150]
The Second apply of the same checks shouldn't affect the result

**Comment by vrom911** [comment]
Another property for `applyCheck`:

```haskell
ignore x >> include x === id
```

Is this correct understanding, @chshersh ?

**Comment by chshersh** [comment]
@vrom911 Wow, nice idea! This indeed looks like a valid property. Ignoring some check, and then including it back shouldn't change the resulting set of inspections.
