### ISSUE TITLE
Count total number of inspections

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#154]
After `applyChecks`, the number of inspections is not the number of all inspections anymore. Need to find the way to count that differently (but yet, efficiently).

**Comment by chshersh** [comment]
The simplest solution I can think of is having a `HashSet` of inspection ids in the analysis and add each new set to the result and taking the size of this set at the end.

**Comment by vrom911** [comment]
Yes, neat idea. It is also would be useful to have the whole set for the report :+1:
