### ISSUE TITLE
Foldable methods on possibly error-prone structures

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#176]
Candidates: tuples and `Maybe`
e.g `maximum (2, 1)`

**Comment by chshersh** [comment]
I propose to have a single inspection for this, instead of having multiple inspections for each combination of type and method...

**Comment by chshersh** [comment]
Another proposal: in the first version of Stan we can simply forbid all methods of the `Foldable` typeclass for tuples, Maybe and Either. But in the future, when GHC starts tracking instance usage evidence in HIE files, we can forbid _any_ function with the `Foldable` typeclass applied to those data types.
