### ISSUE TITLE
Calculate project health

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#182]
How can we count project health? I imagine some formula depending on the total number of inspections, the total number of LOC and the number of found observations.

**Comment by chshersh** [comment]
Here is a simple first-iteration formula for calculating project health (in percentages):

```
(1 - uniqueTriggeredInspections / totalStanInspections) * 100
```

Short explanation and motivation:

1. 100% for projects that don't have any warnings.
2. Counting only unique inspections (not the number of observations) because if a person not aware of some possible vulnerability, it will happen several times.
3. The formula doesn't depend on the project size, since bigger projects already have more chances of triggering more inspections.

And my proposal for colour codes:

1. Healthy project: 100%, **green** :green_heart: :green_apple: 
2. A project a bit under the weather: >= 80% && < 100, **yellow**, :yellow_heart: :warning: 
3. Project has a lot of problems: >= 40% && < 80%, **orange**, :orange_heart: :exclamation: 
4. Unhealthy project: < 40%, **red**, :broken_heart: :no_entry: 

Alternative ideas for formulas:

1. Number of modules without observations `/` total number of modules

We can even include several metrics (numbers) in the final report :slightly_smiling_face:

**Comment by vrom911** [comment]
I like this idea, @chshersh :bulb: . To me, this sounds fairer than the one with modules and it represent the picture better in this case (especially on small projects).
Let's go with that!
