### ISSUE TITLE
Create Summary Section

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#190]

**Comment by chshersh** [comment]
A few ideas for the summary section:

1. Project health (proposed in #182)
2. Display the most popular inspection (has the most number of observations)
3. Display the most popular category (with a message like "Pay more attention to ... issues")
4. Display the most popular severity 

I think, the section can look like this:

### Summary

Short summary of the Static Analysis

* Project health: 67% (emojis, bars, colours, status etc.)
* Inspection the project has most troubles with: STAN-0001
* You should pay more attention to issues with the following categories: List, Partial, Infinite
* The highest severity is ... which is good/bad/...
