### ISSUE TITLE
Handle negation patterns in types better

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#193]
PR #192 implements boolean patterns. But they can't be used. For example, if I specify the pattern for `pred` like this:

```haskell
neg $ integer |-> (?)
```

The function of type `Integer -> Integer` matches the pattern. Because our algorithm tries to match every pattern in the list. And the `pred` function in the following code:

```haskell
foo :: Integer -> Integer
foo = pred
```

Has two types:

```haskell
1. Integer -> Integer
2. forall a . Enum a => a -> a
```

The first type doesn't match the pattern, but the second one does, that's why we still see the inspection. The second case (comparison with the type variable) happens here:

https://github.com/kowainik/stan/blob/cdd8ed9e2768796d844f3d45a35a09a5add45fa0/src/Stan/Hie/MatchType.hs#L65-L66

Something needs to be done with this to make everything works...

**Comment by vrom911** [comment]
We can introduce another pattern — `PatternExact`, and do not match others if this one is specified. What do you think about that?
