### ISSUE TITLE
Create configuration

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#24]
It's probably a good idea to create some configuration file, if people want to ignore some checks. I'm thinking about having `.stan.toml` file in repository with the syntax like:

```toml
ignore =
    [ { id = "HEAD" }
    , { id = "TAIL" }
    , { severity = "Warning" }
    ]
```

I'm using an array of tables of custom types. It can be written in a more verbose (but probably less noisy way):

```toml
[[ignore]]
id = "HEAD"

[[ignore]]
id = "TAIL"

[[ignore]]
severity = "Warning"
```

Basically, you can specify a list of conditions you want to ignore. In this case: all inspections with ids `HEAD` and `TAIL` and all inspections with severity `Warning` (and lower?). Let me know what do you think!

Or maybe you have more ideas about what we can put in the config? It would be also nice to be able to extend `stan` externally, so people can create their own checks (like forbid partial functions from external packages), but I feel like this deserves a separate issue and a separate discussion...

**Comment by vrom911** [comment]
Oh, this is amazing!

I would add grouping setting later. By default, we group by modules, but maybe it could be configurable for e.g. grouping by inspection. But I guess it could be done later.

Also, I can imagine how per-module ignore can be helpful. Need to think how with would affect our scheme.

**Comment by chshersh** [comment]
@vrom911 Grouping by categories or by severity or by inspection id is an excellent idea :+1: I'd love to see this done in the future.

> Also, I can imagine how per-module ignore can be helpful. 

Or maybe even by directories...

**Comment by chshersh** [comment]
Idea for the configuration type:

```haskell
data Config = Config
    { configIgnore :: [Ignore]
    , configGroupBy :: GroupBy
    }

data GroupBy
    = ByModule
    | ByCategory
    | ByInspection

data Ignore
    = IgnoreInspection (Id Inspection)
    | IgnoreObservation (Id Observation)
    | IgnoreSeverity Severity
    | IgnoreModule Text
    | IgnoreDirectory FilePath
    | IgnoreCategory Category
```

With this approach we can extend our ignoring and grouping later if we want to add something fancy, like, ignore by regular expression or some different grouping.

What do you think about this idea?

**Comment by vrom911** [comment]
Looks good, @chshersh !

I was thinking about having something opposite to `ignore` (`include`?) as well. Do you think that if we decide to go with that, the proposed scheme should be changed significantly? Or could it be extendable enough to consider all kinds of ignoring/including?

**Comment by chshersh** [comment]
@vrom911 That's also an excellent proposal :ok_hand: Having some whitelist and blacklist strategy is nice if people want to check only for a subset of checks. It's an interesting question, how to define priority for them, but the following logic seems reasonable to me:

1. If nothing is specified, then all inspections are checked.
2. If only whitelist is written, then only specified inspections are checked.
3. If only blacklist is written, then all inspections except ignored are checked.
4. If both are specified, then we check only whitelisted exceptions without ignored. In this scenario, blacklisting takes priority over whitelisting.

For 4: it's possible to implement a reversed strategy, but I'm not sure what is common and what is more intuitive... Regarding the names: I like `include / ignore` :+1: Maybe these two words look too similar, this is the only concern, but otherwise looks good.

We can reuse the same type for both filtering criteria in the `Config` type:

```haskell
data Config = Config
    { configInclude :: [Filtering]
    , configIgnore  :: [Filtering]
    , configGroupBy :: GroupBy
    }
```

We only need to come up with the data type name..

**Comment by chshersh** [comment]
@vrom911 Ideas for naming (both CLI arguments and data type fields):

* `check` for whitelisting
* `ignore` for blacklisting
* `Check` for data type name, so it will be like this

```haskell

data Config = Config
    { configChecks  :: [Check]
    , configIgnore  :: [Check]
    , configGroupBy :: GroupBy
    }

data Check
    = CheckInspection (Id Inspection)
    | CheckObservation (Id Observation)
    | CheckSeverity Severity
    | CheckModule Text
    | CheckDirectory FilePath
    | CheckCategory Category
```

**Comment by vrom911** [comment]
Another useful candidate for ignoring ­— files/directories.

```toml
[[ignore]]
file = "src/MyFile.hs"
```

But this reminds me of the use case when you want to ignore only one type of inspections in the concrete file:

```toml
[[ignore]]
id = "STAN-0001"
in = "src/MyFile.hs"
```

And probably more other useful combinations of ignorance?

**Comment by chshersh** [comment]
@vrom911 Good point :+1: I indeed can see how this can be helpful. So we want to be able to compose some types of checks. I can see the following possible combinations:

1. Everything in a file/module/directory.
2. Specific checks in a file/module/directory. 

In that case, we can model such situations by introducing a data type for scopes of checks. What do you think about the following data types:

```haskell
data Config = Config
    { configChecks  :: [Check]
    , configIgnore  :: [Check]
    , configGroupBy :: GroupBy
    }

-- TODO: it doesn't make sense to have both Nothing, so we need a data type like 'These'
-- data These a b = This a | That b | Both a b
data Check = Check
    { checkFilter :: Maybe CheckFilter
    , checkScope  :: Maybe CheckScope
    }

data CheckFilter
    = CheckInspection (Id Inspection)
    | CheckObservation (Id Observation)
    | CheckSeverity Severity
    | CheckCategory Category

data CheckScope
    = CheckScopeFile FilePath
    | CheckScopeDirectory FilePath
    | CheckScopeModule ModuleName
```

And in the config this can look like this:

```toml
# ignore everything in the test/ directory
[[ignore]]
directory = "test/"

# ignore specific inspection everywhere
[[ignore]]
id = "STAN-0002"

# ignore specific inspection only in a specific file
[[ignore]]
id = "STAN-0001"
file = "src/MyFile.hs"
```

What do you think?

**Comment by vrom911** [comment]
Yes, something like this should work smoothly with all sort of scenario.
I wonder if it would be possible to write such codex with `tomland` :thinking:
