### ISSUE TITLE
Extend Severity data type

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#30]

**Comment by chshersh** [comment]
A few ideas from the top of my head (in order of increasing severity):

1. `Performance` (e.g. for slow functions and space leaks) — blue
2. `PossibleBug` (e.g. `[0..length xs]`) — magenta
3. `Warning` (e.g. for partial functions) — yellow
4. `Error` (e.g ???) — red

**Comment by chshersh** [comment]
@vrom911 A new idea:

1. `Style` (e.g. type signatures in `where`, missing `infix`) — cyan
2. `Performance` (e.g. for slow functions and space leaks) — blue
3. `PossibleBug` (e.g. `[0..length xs]`) — magenta
4. `Warning` (e.g. for partial functions) — yellow
5. `Error` — red — reserved for future. I imagine something like `putStrLn undefined` is an `Error`.

**Comment by vrom911** [comment]
I like that!

And we can already implement the `Error` one with the `undefined` function, it is easily detectible.
