### ISSUE TITLE
Missing documentation on ignoring inspections

### ISSUE THREAD

**Issue by ShrykeWindgrace** [kowainik/stan#309]
Hi!

Thanks for this tool! I toyed around running `stan` against my toy projects, and it seems that I can not ignore inspections.

I tried to run a command `stan ignore --id=ID` for different variants of ID: `STAN-0206`, `0206`, `[0206]`, and `[STAN-0206]`;  they all result in a warning
`Unrecognised Observation IDs: ` and, among other things, the observations for my code tagged `STAN-0206` which I tried to ignore.

Hence my question - what is the correct syntax to ignore inspections?

$ stan --version
Stan v0.0.0.0
 ➤ Git revision: 6521fa18a0d36f261f0e184aa94e9109f02bad01
 ➤ Commit date:  Mon Jun 22 09:37:53 2020 +0100

Both my project and `stan` are build against `nightly-2020-06-21` with `ghc-8.10.1`.
Win 10 (1809), git bash, stack 2.3.1.

**Comment by chshersh** [comment]
@ShrykeWindgrace To ignore inspection, you need to use the `check` command. For example, to ignore a particular inspection everywhere:

```shell
$ stan check --exclude --id=STAN-0206 --scope-all
```

The `ignore` option is to ignore resulting observations. We will improve the documentation to provide more examples of CLI.

**Comment by ShrykeWindgrace** [comment]
Great, thank you very much!
