### ISSUE TITLE
Store inspections in 'HashMap'

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#31]
See https://github.com/kowainik/stan/pull/28#discussion_r407524603

**Comment by chshersh** [comment]
I was thinking about this problem for a while, and the only solution I see, that doesn't involve massive type-level magic, is the following:

1. Once #26 is done, we can have a list of all known ids and we can write tests ensuring that looking up by known ID doesn't result into an error.
2. In addition we can write a test that checks that all inspection IDs are unique (there are no duplicates), just to double-check ourselves.

This way all calls to the `getInspectionById` function will be safe. How does it sound?

Another question, should we change the list of all inspections from the list type to something like `HashMap`? For more efficient lookups by id.

**Comment by vrom911** [comment]
That sounds good. I think we won't be able to give more guaranties.
I think that having `HashMap` would be very important. Nice catch, @chshersh !

**Comment by chshersh** [comment]
The testing part of this issue is done. So I'm renaming it to change the type of the global list of all inspections to `HashMap`.
