### ISSUE TITLE
WIN10: commitAndReleaseBuffer: invalid argument

### ISSUE THREAD

**Issue by tuomohopia** [kowainik/stan#312]
I'm getting the following error when running the freshly compiled `stan` on Windows 10 Powershell:
```
stan.exe: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
```

I simply run `stan` in my project's folder. `stan report` gives the same output. Running `stan --version` outputs this:
```
Stan v0.0.0.0
 stan.exe: <stdout>: commitBuffer: invalid argument (invalid character)
```

`stan --help` displays the help normally, however.

System:
* GHC 8.8.3
* Stack 2.3.1

**Comment by nxths** [comment]
Am seeing identical behavior in Windows 10 powershell and WSL (calling stan.exe), with GHC-8.10.1 and stack-2.3.1

**Comment by vrom911** [comment]
This seems to be a systems error rather than the tool itself.

I was reading this thread, and there is a lot of useful stuff in here: https://gitlab.haskell.org/ghc/ghc/-/issues/8118

I will add `setLocaleEncoding utf8` in Stan meanwhile, though it may or may not resolve the issue.

Btw, we have a CI check for Windows and it works and outputs everything as it should, that is why this issue was not possible to catch beforehand — see Dogfooding section on our CI https://github.com/kowainik/stan/runs/794528335

**Comment by vrom911** [comment]
@tuomohopia @nxths I have set it to `utf8`. It should work for you now. Additionally, you can try to set env vars locally.
All changes are in master now, and you can check it out and let us know if it helps.

**Comment by nxths** [comment]
@vrom911 thanks for the explanation + fix, this is working on my machine now

**Comment by tuomohopia** [comment]
I confirm it works now on my PC too. Just the pretty printing a bit haywire:
```
           Stan's Summary:
ÔöÅÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö│ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöô
Ôöâ Analysed modules            Ôöâ 2      Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Analysed Lines of Code      Ôöâ 141    Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Total Haskel2010 extensions Ôöâ 4      Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Total SafeHaskel extensions Ôöâ 0      Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Total checked inspections   Ôöâ 44     Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Total found observations    Ôöâ 1      Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Total ignored observations  Ôöâ 0      Ôöâ
ÔöúÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔòïÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö½
Ôöâ Project health              Ôöâ 97.73% Ôöâ
ÔöùÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔö╗ÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöüÔöø

```
