### ISSUE TITLE
Name collision

### ISSUE THREAD

**Issue by rybern** [kowainik/stan#314]
Just pointing out that there is already a popular probabilistic programming language called Stan:
https://github.com/stan-dev
https://mc-stan.org/
Stan has connections to Haskell (e.g. https://zenodo.org/record/1465992) and also has connections to static analysis.

This tool looks very cool to me (I'm a new user!), but the naming is a bit unfortunate. Is there any chance of disambiguating it given that this is in beta and Stan is a 5+ year old project?

**Comment by vrom911** [comment]
Hey @rybern! 
Usually, for Haskell, the indicator of the name usage is Hackage. If the name is taken there, that means that a) you won't be able to upload such project and b) the name is already used for something else in the Haskell community.
For Stan the name was vacant. And we already uploaded the package on Hackage, so I don't think that it is subject to change at the moment.

The name clashes are inevitable in different communities. And it is simply not possible to know about every single name out there. Our metric was that this name is not used in the Haskell community. Unfortunately, we are not participating in the probabilistic community. But as there are no clashes in the fields and purposes, I don't think it creates any problems at all.
