### ISSUE TITLE
Compare to hlint

### ISSUE THREAD

**Issue by maralorn** [kowainik/stan#318]
Thank you for stan, it looks very interesting.

Can you maybe explain somewhere in the documentation how stan differs from hlint in terms of goals/scope/design decisions?

**Comment by vrom911** [comment]
Thanks, @maralorn!

We added the [Other Tools](https://github.com/kowainik/stan#other-tools) section in README, hope it answers your questions. 
Let us know if you have any more questions.

**Comment by maralorn** [comment]
Thank you @vrom911 . I had another look at the documentation and I understand the difference now. Looking really forward to using stan in my projects.
