### ISSUE TITLE
Add a JSON output format

### ISSUE THREAD

**Issue by TomMD** [kowainik/stan#323]
Stan lacks a machine-parsable output format, such as JSON.  We should add one!

**Comment by chshersh** [comment]
If the goal is to have a machine-parseable output format then TOML is a more favourable choice, since we already depend on the `tomland` library. Bringing new dependencies to the project will make the installation process slower for all Stan users, even if they don't need machine-parseable output.

**Comment by TomMD** [comment]
OK, thanks for the direction.  Making a full TOML is a bit more work both because tomland affords less automation and encourages a bidirectional codecs, while the envisioned JSON would be lossy.

I [hacked up a JSON](https://github.com/TomMD/stan/tree/feature/basic-json-output) that will suffice until we get the toml and I also get a good toml/json translation external to stan.  Will keep the toml task on my radar.
