### ISSUE TITLE
Add --solution option in CLI to hide/show solution

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#33]
Some would like to have their output short and omit hints/solutions in there.

**Comment by chshersh** [comment]
@vrom911 Should we display solution by default and hide it with the `--no-solution` or `--hide-solution` option or vice versa?

**Comment by vrom911** [comment]
I would prefer to have a solution in the first place and only turn it off by the specific option. I think that firstly it is beneficial info and should come as the part of the tool that we want to provide. Secondly, this information should be discoverable immediately, but if it would require you to provide some additional actions, I am sure that some potential users could just miss it.
