### ISSUE TITLE
Add --non-verbose option in CLI

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#35]
For very short one-line output per observation:

```
$ stan --non-verbose
 * [1-STAN-001] WARNING <src/Example.hs(20:4-20:8)> Partial: head
 * [2-STAN-001] ERROR   <src/Example.hs(20:4-20:8)> Partial: head
```
^ the output format should be discussed better :slightly_smiling_face:

**Comment by chshersh** [comment]
@vrom911 This output format is already perfect, there's nothing to discuss :ok_hand: I like the idea! An alternative idea for the option name: `--short`
