### ISSUE TITLE
CLI command to show known Inspections

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#36]
Show the list of all inspections with some info + ability to show more about particular inspection by the given ID.

**Comment by chshersh** [comment]
Another idea: add `--filter` option (or better name) to display only subset of inspections. To filter by category (like, only partial functions). Or a combination of options `--keep/ignore`, so users can call like this:

```
stan inspection --keep Infinite --ignore Partial --ignore SpaceLeak
```
