### ISSUE TITLE
hie files for the target project

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#4]
Should we assume that they are present? Or should we create them during the run?
In the first option, we should add instructions, but with the second option, we need to decide how to make it more efficiently.

**Comment by chshersh** [comment]
I think we can assume that they are present and add instructions on how to produce these files in our README. So with this approach, we won't worry about keeping those files up-to-date.

**Comment by vrom911** [comment]
That is a good point. Also, we won't need to clean up after work.

It would be nice if all projects would generate the practice of always create `.hie` files, that could be beneficial for many tools :+1:
