### ISSUE TITLE
Maybe update to newer pretty-simple?

### ISSUE THREAD

**Issue by maralorn** [kowainik/stan#408]
stan has a pretty-simple 3.2.0.0 ^>= bound.

There already is pretty-simple 4.0.0.0.

Is there a reason not to bump those version bounds? It seems to compile fine.

This is not urgent, but keeping all those bounds up-to-dates helps with packaging, in this case for nixos.

**Comment by chshersh** [comment]
Updating to a newer version of pretty-simple sounds good to me. No strong reason for keeping the old version, only the lack of free time. Feel free to contribute the PR!

Ideally, it would be also nice to see the [output of the debug information following these steps](https://github.com/kowainik/stan/wiki/Development#view-hie-ast-of-a-file) to make sure that the latest version of `pretty-simple` doesn't make the output worse. We use `pretty-simple` to debug HIE AST in `ghci`.
