### ISSUE TITLE
8.10.7 release?

### ISSUE THREAD

**Issue by unhammer** [kowainik/stan#496]
```
stan-0.0.1.0-Linux-ghc-8.10.1: stan-0.0.1.0-Linux-ghc-8.10.1: panic! (the 'impossible' happened)
  (GHC version 8.10.1:
        readHieFile: hie file versions don't match for file: .hie/Types.hie Expected 8101 but got 8107
```

(btw I tried your github workflow on a different project, had to update some deprecated actions, https://raw.githubusercontent.com/unhammer/bin-your-stars/master/.github/workflows/release.yml if it's of use)

**Comment by tomjaguarpaw** [comment]
I'm not sure exactly what you mean. A special release shouldn't be required for 8.10.7, but you do have to specifically compile `stan` for the version of GHC that you compile your target code with.

Anyway, you should be able to use GHC up to 9.4 with `stan` now:

https://hackage.haskell.org/package/stan-0.1.0.0

Unless you're still having problems I'll close this issue in due course.
