### ISSUE TITLE
Fixing Github actions caching

### ISSUE THREAD

**Issue by 0rphee** [kowainik/stan#529]
Hi! I saw your posts on [Discourse](https://discourse.haskell.org/t/release-stan-extending-support-to-ghc-9-6/7888) and figured that maybe I could help a little with the caching issues.

Checking the last two CI runs, I found that for the windows ghc 9.6.3 case, the cache keys were the same, yet there was no cache hit! Weirdly enough, if the cache keys were the same for the windows runs, they weren't for the 9.6.3 linux and macos runs that I checked! (Here are the windows runs with the same keys, but with no cache hit: https://github.com/kowainik/stan/actions/runs/6537397845/job/17751158155, https://github.com/kowainik/stan/actions/runs/6537515014/job/17751527928)

Anyways. I checked other repos looking for differences in caching strategies and the only difference I found is that the stan CI doesn't run `cabal update` before freezing and looking for the cache. 

I created a [fork](https://github.com/0rphee/stan/actions/runs/6550668746/job/17790256402), made the changes and after a cursory look in the logs, it seems to have worked. Here are two consecutive runs: https://github.com/0rphee/stan/actions/runs/6550149679/job/17788640195 & https://github.com/0rphee/stan/actions/runs/6550668746/job/17790256402 

Also, I've changed the [haskell setup action](https://github.com/haskell/actions), as it has been deprecated in favor of [this action](https://github.com/haskell-actions/setup).

I was about to create a PR, but I saw in your post that I should create an issue before so here I am!

**Comment by 0rphee** [comment]
Oh, and tell me if I need to reword the commits according to [CONTRIBUTING.md](https://github.com/kowainik/.github/blob/74c26af31623378c26145ef7336cb6b085c10bd1/CONTRIBUTING.md)

**Comment by tomjaguarpaw** [comment]
Resolved by https://github.com/kowainik/stan/pull/530
