### ISSUE TITLE
Single-pass functions detection in Analysis

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#55]
Currently, we do AST search separately for each inspection. We can think on a way to do it in a single-pass for every module.

**Comment by chshersh** [comment]
@vrom911 Excellent catch! I haven't thought about that, but it would be really good to traverse the AST only once. Maybe we can somehow pass a list of `NameMeta`s to the analysis function and combine those lists from different inspections :thinking:

**Comment by chshersh** [comment]
I'm thinking about possible ways to implement a single pass traversal, and what would be the best way to implement in in a maintainable way. I will write below one possible solution for this problem I see at the moment. Maybe it can be improved, or maybe 

Currently, we have the following function:

```haskell
analyseNameMeta
  :: Id Inspection
  -> NameMeta
  -> HieFile
  -> Observations
```

This function traverses `HieAST` and returns a list of observations, found in the whole AST for a single inspection. I'm thinking about using the _visitor programming pattern_ to implement this in a single-pass. A short overview of the approach:

1. Store resulted observations in a state.
2. Implement monadic functions that tell what to do when we visit a specific part of the AST. Currently, we need to do something on specific names and specific AST nodes (see #65).
3. Create a function that combines all inspections into a single visitor. So we can traverse all inspections only once, and then use built visitor to traverse each AST only once.

So, this idea expressed shortly:

```haskell
data Visit = Visit
    { visitNameMeta :: NameMeta -> Observations
    , visitNode :: Node TypeIndex -> Observations
    }

defaultVisit :: Visit
defaultVisit = Visit
    { ... = \_ -> pass
    , ... = \_ -> pass
    }

inspectionsVisitor :: [Inspection] -> Visit
inspectionsVisitor = foldl' visitInspection defaultVisit
  where
    visitInspection :: Inspection -> Visit -> Visit

analyseAst :: Visit -> HieFile -> State Observations ()
analyseAst ... pseudocode ... = case node of
    NameMeta naneMeta -> addToState $ visitNameMeta nameMeta
    Node node -> addResult $ visitNode nameMeta
```

Does this make sense? I'm not sure that the final implementation will be exactly the same, this is just an idea :slightly_smiling_face: Maybe I'm missing some obvious solution...
