### ISSUE TITLE
Better interface

### ISSUE THREAD

**Issue by 0rphee** [kowainik/stan#551]
The `hls-stan-plugin`, lacked the capability to take into account `.stan.toml` files. While I've managed to make it work by roughly replicating what `runStan` does in the `Stan` module, it was recommended to add a more packaged solution to `stan` itself, and rely on those functions instead. 

The primary goal of this would be to break up `runStan` into various functions that can be used by hls. At this moment I'm trying out how that would look like and hopefully submit a PR, but if you have any recommendations, they are of course very welcome!

Here it's the relevant PR from hls, to get a better overview of what this would help with. 
https://github.com/haskell/haskell-language-server/pull/3914

**Comment by tomjaguarpaw** [comment]
Is this issue completed by https://github.com/kowainik/stan/pull/552, or is there more to it?

**Comment by 0rphee** [comment]
I think its fine to close it.
