### ISSUE TITLE
Inspections for unsafe `Scientific` methods

### ISSUE THREAD

**Issue by jlavelle** [kowainik/stan#578]
Several of the `Scientific` instances (`Num`, `Fractional`, `Real`, and `RealFrac`) come with warnings about partiality or potential for excessive memory consumption, and it would be nice to have warnings for those. Would you accept a PR adding those checks?

I'm not clear on exactly what category the memory-related checks should fall under.

**Comment by tomjaguarpaw** [comment]
> Would you accept a PR adding those checks?

Yes, that would be welcome, thanks.
