### ISSUE TITLE
Decide on the console output format

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#8]
How to code warnings/errors.
What to include? (loc, filepath, module name, more?)

**Comment by chshersh** [comment]
I'd like to have a pretty and colourful output with colour-coded categories of warnings. I'm not sure what will be the best results, but here is one option from top of my head.

For example, if a module has the following content:

```haskell
module Example where

example = head []
```

The output can look like this:

```
[Possible bug]: Usage of partial function 'head'
Module: Example, Path: src/Example.hs, Location: line 3, column 11

  2 ┃
  3 ┃ example = head []
  4 ┃           ^^^^
```

Alternative ideas:

* Group by modules and use fancy borders. Like this:

```
      C:\Users\Example\Documents\Examples.hs:44:10-15
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ [Possible bug] Usage of partial function 'head'
┃
┃  2 ┃
┃  3 ┃ example1 = head []
┃  4 ┃            ^^^^
┃
┃ [Possible bug] Usage of partial function 'init'
┃
┃  5 ┃
┃  6 ┃ example2 = init []
┃  7 ┃            ^^^^
```

Any ideas and improvement suggestions are appreciated! I really want to have a fancy and readable output with helpful information, so feel free to propose any improvements :slightly_smiling_face:

**Comment by vrom911** [comment]
Neat :+1: Mm, I like grouping! Later we can write different options on grouping.

I was also thinking of having some hint on how to resolve the issue.

**Comment by chshersh** [comment]
@vrom911 Great idea on having a hint on how to fix! This would be really awesome!

**Comment by chshersh** [comment]
@vrom911 What do you think about the following version? Added solution, inspection id and categories.

```
 File:         src/Example.hs
 Module:       Example
 Observations: 2
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ [Warning] Usage of partial function 'head' #Partial #Essential   --- [HEAD]
┃
┃  2 ┃
┃  3 ┃ example1 = head []
┃  4 ┃            ^^^^
┃
┃   Posible solutions:
┃   * Use 'NonEmpty'
┃   * Manual pattern-matching
┃
┃ [Warning] Usage of partial function 'head' #Partial #Essential   --- [INIT]
┃
┃  5 ┃
┃  6 ┃ example2 = init []
┃  7 ┃            ^^^^
┃
┃   Posible solutions:
┃   * Use 'NonEmpty'
┃   * Manual pattern-matching
```

**Comment by vrom911** [comment]
Wonderful! Looking at your example I came up with a few more idea. What do you think if we provide a little more info to user. Like:

```
 File:         src/Example.hs
 Module:       Example
 Observations: 2
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
┃ *  ID:            1-STAN-0001-HEAD
┃    Severity:      WARNING
┃    Desc:          Usage of partial function 'head' 
┃    Inspection ID: STAN-0001-HEAD (maybe this is link)
┃    Category:      #Partial #Essential
┃
┃  2 ┃
┃  3 ┃ example1 = head []
┃  4 ┃            ^^^^
┃
┃   Posible solutions:
┃   * Use 'NonEmpty'
┃   * Manual pattern-matching
```

**Comment by chshersh** [comment]
@vrom911 Your suggestion is awesome :heart_eyes: Let's implement it this way :+1:
