### ISSUE TITLE
When cabal file is not found get extensions per module instead of none

### ISSUE THREAD

**Issue by vrom911** [kowainik/stan#82]

**Comment by chshersh** [comment]
I just had an idea of how this can be done without much pain:

1. If `.cabal` file is not present, convert `[HieFile]` to `Map FilePath ByteString`.
2. Map values of that `Map` with the parsing function to get `Map FilePath (Either ParseError [OnOffExtension])`.
3. Map values again with key by using the [`mergeCabalAndModule
`](https://github.com/kowainik/extensions/blob/293554f22be585c42da7c9480ab33fe46288bd30/src/Extensions.hs#L147) function from `extensions`, partially applied to empty list, to get `Map FilePath ExtensionsResult`.

Does it sound okay? Or maybe I'm missing something?..

**Comment by vrom911** [comment]
Yep, this sounds right.
The only thing that bothers me a little at this point is that we won't be able to indicate the difference between when we do have a cabal file and when we don't in the report section of extension numbers. Do you think that this is not a big deal?

**Comment by vrom911** [comment]
This brings me to the thought: what if we have a `ReportSettings` data type. We already can put the `verbosity` level in there, and I am sure much more will come, what do you think, @chshersh ?

**Comment by chshersh** [comment]
@vrom911 Excellent points 👍  I think I would like to see two different numbers of how many extensions were defined in the module exactly and how many were used in total including the `.cabal` file. This can be an interesting statistic! And regarding `ReportSettings`: nice idea! I also think that we will have a lot more options to come.
