### ISSUE TITLE
Count the number of analyzed modules

### ISSUE THREAD

**Issue by chshersh** [kowainik/stan#9]
Also, how should we display this information in the terminal? I guess, at the beginning of the output is fine.

**Comment by vrom911** [comment]
Or in the end, so you won't need to scroll up to see that.
It could be some summary at the bottom, something like:

```
----------------------------------
Analyzed modules: 5
Analyzed loc: 100
Number of potential vulnerabilities found: 3
...
```

**Comment by chshersh** [comment]
@vrom911 Good catch on putting the information at the end :+1: Agree with this reasoning.
